# Generated by Django 5.0.2 on 2024-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(null=True, upload_to='teahcer_profile_imgs/')),
                ('skills', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
                ('otp_digit', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Teachers',
            },
        ),
    ]
