# Generated by Django 5.0.3 on 2024-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default='shyam'),
            preserve_default=False,
        ),
    ]
