# Generated by Django 5.0.2 on 2024-05-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacherstudentchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otp_digit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
