# Generated by Django 5.0.3 on 2024-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(default='sdnfkjsdf', upload_to='course_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(default='ksjdfkjskldfjmkljsdiofjoisdjnf'),
            preserve_default=False,
        ),
    ]
