# Generated by Django 5.0.3 on 2024-03-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_featured_img_course_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
