# Generated by Django 5.0.2 on 2024-05-28 08:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='chapter_videos/'),
        ),
    ]
