# Generated by Django 5.0.2 on 2024-06-01 10:51

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='chapter_videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
