# Generated by Django 5.0.2 on 2024-06-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chapter_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='AttempQuiz',
        ),
        migrations.DeleteModel(
            name='CourseQuiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
    ]
