# Generated by Django 5.0.2 on 2024-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sell',
        ),
    ]
