# Generated by Django 5.0.2 on 2024-04-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_courserating_options_alter_courserating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
