# Generated by Django 5.0.2 on 2024-04-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notification'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
    ]
