# Generated by Django 5.0.2 on 2024-04-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_attempquiz_right_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
