# Generated by Django 5.0.2 on 2024-05-06 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_studentcourseenrollment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_duration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
