# Generated by Django 5.0.2 on 2024-05-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_chapter_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
    ]
