# Generated by Django 5.0.2 on 2024-05-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_course_teacher_alter_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='otp_digit',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='main.teacher'),
        ),
    ]
